// ─── HIPAA Security Rule Controls ─────────────────────────────────────────
// Health Insurance Portability and Accountability Act
// Technical Safeguards (§164.312) — mapped to Zyphorix Guard evidence

import type { SOC2Control } from './soc2-controls';

export const HIPAA_CONTROLS: SOC2Control[] = [
  {
    id:'HIPAA-164.312(a)(1)', category:'CC',
    title:'Access Control — Unique User Identification',
    description:'Assign a unique name and/or number for identifying and tracking user identity.',
    evidenceType:['ACCESS_CONTROL','AUDIT_LOG'],
    automatedCheck:true,
    howZyphorixHelps:'Team management assigns unique accounts. Audit logs track actions by individual user ID.',
  },
  {
    id:'HIPAA-164.312(a)(2)', category:'CC',
    title:'Access Control — Emergency Access Procedure',
    description:'Establish procedures for obtaining necessary ePHI during an emergency.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Document your emergency access procedures.',
    remediation:'Create and document an emergency access procedure for ePHI systems.',
  },
  {
    id:'HIPAA-164.312(a)(3)', category:'CC',
    title:'Access Control — Automatic Logoff',
    description:'Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload session timeout configuration documentation.',
    remediation:'Configure automatic session timeouts on all ePHI access systems.',
  },
  {
    id:'HIPAA-164.312(a)(4)', category:'C',
    title:'Access Control — Encryption and Decryption',
    description:'Implement a mechanism to encrypt and decrypt ePHI.',
    evidenceType:['CLOUD_FINDING','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'AWS cloud scan verifies S3 encryption status and detects unencrypted storage that may contain ePHI.',
    remediation:'Run cloud scan to identify unencrypted S3 buckets and enable default SSE-KMS encryption.',
  },
  {
    id:'HIPAA-164.312(b)', category:'CC',
    title:'Audit Controls',
    description:'Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use ePHI.',
    evidenceType:['AUDIT_LOG','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'Comprehensive audit logging of all user actions with timestamps. Log ingestion captures system-level audit trails. Cloud scan checks CloudTrail is enabled.',
  },
  {
    id:'HIPAA-164.312(c)(1)', category:'C',
    title:'Integrity — Authentication Mechanism',
    description:'Implement electronic mechanisms to corroborate that ePHI has not been altered or destroyed in an unauthorized manner.',
    evidenceType:['CLOUD_FINDING','MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'S3 versioning findings indicate whether data integrity mechanisms are in place.',
    remediation:'Enable S3 versioning and MFA delete on buckets containing ePHI.',
  },
  {
    id:'HIPAA-164.312(d)', category:'CC',
    title:'Person or Entity Authentication',
    description:'Implement procedures to verify that a person or entity seeking access to ePHI is the one claimed.',
    evidenceType:['MFA_STATUS','ACCESS_CONTROL'],
    automatedCheck:true,
    howZyphorixHelps:'IAM MFA findings verify that multi-factor authentication is enforced. RBAC documentation shows authentication requirements.',
    remediation:'Run cloud scan to verify MFA is enabled for all IAM users with access to ePHI systems.',
  },
  {
    id:'HIPAA-164.312(e)(1)', category:'CC',
    title:'Transmission Security — Integrity Controls',
    description:'Implement security measures to guard against unauthorized access to ePHI that is being transmitted over an electronic communications network.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload TLS configuration and network security documentation.',
    remediation:'Document TLS 1.2+ enforcement on all ePHI transmission channels.',
  },
  {
    id:'HIPAA-164.312(e)(2)', category:'C',
    title:'Transmission Security — Encryption',
    description:'Implement a mechanism to encrypt ePHI whenever deemed appropriate.',
    evidenceType:['CLOUD_FINDING','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'S3 encryption findings and network security analysis verify encryption in transit and at rest for ePHI.',
  },
  {
    id:'HIPAA-164.308(a)(1)', category:'CC',
    title:'Administrative — Risk Analysis',
    description:'Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to ePHI.',
    evidenceType:['SCAN_HISTORY','VULNERABILITY_SCAN','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'Regular security scans with risk scoring, MITRE mapping, and cloud vulnerability findings directly satisfy the HIPAA risk analysis requirement.',
  },
  {
    id:'HIPAA-164.308(a)(5)', category:'CC',
    title:'Administrative — Security Awareness Training',
    description:'Implement a security awareness and training program for all members of its workforce.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload security training completion records.',
    remediation:'Conduct and document annual security awareness training for all staff with ePHI access.',
  },
  {
    id:'HIPAA-164.308(a)(6)', category:'CC',
    title:'Administrative — Security Incident Procedures',
    description:'Implement policies and procedures to address security incidents.',
    evidenceType:['INCIDENT_LOG','AUDIT_LOG'],
    automatedCheck:true,
    howZyphorixHelps:'Incident management with P1-P4 severity, full timeline, and resolution records directly satisfies HIPAA security incident documentation requirements.',
  },
];
