// ─── PCI DSS v4.0 Controls ────────────────────────────────────────────────
// Payment Card Industry Data Security Standard
// 12 requirements mapped to Zyphorix Guard evidence

import type { SOC2Control } from './soc2-controls';

export const PCI_CONTROLS: SOC2Control[] = [
  {
    id:'PCI-1.1', category:'CC',
    title:'Install and maintain network security controls',
    description:'Network security controls (NSCs) are configured and maintained.',
    evidenceType:['CLOUD_FINDING','ASSET_INVENTORY'],
    automatedCheck:true,
    howZyphorixHelps:'Security group analysis identifies open ports and misconfigured firewall rules. Asset inventory tracks all network-connected assets.',
    remediation:'Run a cloud security scan to identify open security groups and remediate.',
  },
  {
    id:'PCI-2.1', category:'CC',
    title:'Apply secure configurations to all system components',
    description:'Processes and mechanisms for applying secure configurations to all system components are defined and understood.',
    evidenceType:['CLOUD_FINDING','VULNERABILITY_SCAN'],
    automatedCheck:true,
    howZyphorixHelps:'Cloud security scans detect default credentials, unnecessary services, and insecure configurations in AWS resources.',
  },
  {
    id:'PCI-3.1', category:'C',
    title:'Protect stored account data',
    description:'Processes and mechanisms for protecting stored account data are defined and understood.',
    evidenceType:['CLOUD_FINDING','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'S3 encryption findings verify that storage is encrypted at rest. Asset tagging allows marking cardholder data environments.',
    remediation:'Run AWS cloud scan to verify S3 encryption is enabled on all buckets that may store card data.',
  },
  {
    id:'PCI-4.1', category:'CC',
    title:'Protect cardholder data with strong cryptography during transmission',
    description:'Processes and mechanisms for protecting cardholder data with strong cryptography during transmission over open, public networks are defined and understood.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload TLS certificate documentation and network diagrams.',
    remediation:'Document your TLS configuration and upload certificate evidence.',
  },
  {
    id:'PCI-5.1', category:'CC',
    title:'Protect all systems against malware',
    description:'Processes and mechanisms for protecting all systems against malware are defined and understood.',
    evidenceType:['SCAN_HISTORY','VULNERABILITY_SCAN'],
    automatedCheck:true,
    howZyphorixHelps:'File scanning with VirusTotal integration provides multi-engine malware detection. Scan history demonstrates active malware monitoring.',
  },
  {
    id:'PCI-6.1', category:'CC',
    title:'Develop and maintain secure systems and software',
    description:'Processes and mechanisms for developing and maintaining secure systems and software are defined and understood.',
    evidenceType:['VULNERABILITY_SCAN','SCAN_HISTORY'],
    automatedCheck:true,
    howZyphorixHelps:'Continuous vulnerability scanning across URLs, files, and cloud infrastructure. MITRE ATT&CK mapping shows vulnerability context.',
  },
  {
    id:'PCI-7.1', category:'CC',
    title:'Restrict access to system components and cardholder data by business need to know',
    description:'Access to system components and cardholder data is appropriately defined and assigned based on job classification and function.',
    evidenceType:['ACCESS_CONTROL','AUDIT_LOG','MFA_STATUS'],
    automatedCheck:true,
    howZyphorixHelps:'RBAC documentation shows role-based access. Audit logs record all access events. Cloud IAM scan verifies MFA enforcement.',
  },
  {
    id:'PCI-8.1', category:'CC',
    title:'Identify users and authenticate access to system components',
    description:'All users are assigned a unique ID before allowing them to access system components or cardholder data.',
    evidenceType:['ACCESS_CONTROL','MFA_STATUS','AUDIT_LOG'],
    automatedCheck:true,
    howZyphorixHelps:'Team management shows individual user accounts. IAM scan verifies MFA on all AWS users. Login audit logs track authentication.',
    remediation:'Connect AWS account to verify IAM MFA status across all users.',
  },
  {
    id:'PCI-9.1', category:'CC',
    title:'Restrict physical access to cardholder data',
    description:'Processes and mechanisms for restricting physical access to cardholder data are defined and understood.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload physical access control documentation.',
    remediation:'Document physical security measures (locks, cameras, visitor logs) for cardholder data areas.',
  },
  {
    id:'PCI-10.1', category:'CC',
    title:'Log and monitor all access to system components and cardholder data',
    description:'Logging mechanisms are in place to track user activity. Logs are reviewed to identify anomalies or suspicious activity.',
    evidenceType:['AUDIT_LOG','CLOUD_FINDING','SCAN_HISTORY'],
    automatedCheck:true,
    howZyphorixHelps:'Audit logs capture all user activity. Log ingestion API collects logs from all sources. Cloud scan checks CloudTrail and S3 access logging.',
  },
  {
    id:'PCI-11.1', category:'CC',
    title:'Test security of systems and networks regularly',
    description:'Processes and mechanisms for testing the security of systems and networks are defined and understood.',
    evidenceType:['SCAN_HISTORY','VULNERABILITY_SCAN','CLOUD_FINDING'],
    automatedCheck:true,
    howZyphorixHelps:'Regular security scanning satisfies penetration testing and vulnerability scanning requirements. Scan history provides evidence of testing cadence.',
  },
  {
    id:'PCI-12.1', category:'CC',
    title:'Support information security with organizational policies and programs',
    description:'A comprehensive information security policy that governs and provides direction for protection of the entity\'s information assets is known and current.',
    evidenceType:['MANUAL'],
    automatedCheck:false,
    howZyphorixHelps:'Upload your information security policy document.',
    remediation:'Document your information security policy and annual review process.',
  },
];
